#!/bin/bash

echo "🚀 Knowledger Database Setup"
echo "============================"
echo ""
echo "📋 Manual Setup Instructions:"
echo ""
echo "1. Go to your Supabase dashboard: https://supabase.com/dashboard"
echo "2. Select your project"
echo "3. Go to 'SQL Editor' in the left sidebar"
echo "4. Create a new query"
echo "5. Copy and paste the following SQL:"
echo ""
echo "📄 SQL File: $(pwd)/db/01_initial_schema.sql"
echo ""
echo "6. Click 'Run' to execute the migration"
echo ""
echo "🔍 To verify setup:"
echo "   - Check 'Table Editor' for the new tables"
echo "   - Verify RLS policies in 'Authentication' > 'Policies'"
echo ""
echo "📋 Tables that should be created:"
echo "   - users"
echo "   - workspaces" 
echo "   - workspace_members"
echo "   - projects"
echo "   - knowledge"
echo "   - knowledge_relationships"
echo ""
echo "Next steps after DB setup:"
echo "1. cd api"
echo "2. deno task dev"
echo "3. curl http://localhost:8000/health"